- name: Creazione istanza EC2
  ec2:
    keypair: "{{ keypair }}"
    region: "{{ aws_region }}"
    group_id: "{{ group_id }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    instance_tags:
      Env: "{{ env }}"
      Name: "{{ project_name }}"
    count_tag:
      Env: "{{ env }}"
      Name: "{{ project_name }}"
    exact_count: "{{ instance_count }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    volumes:
      - device_name: /dev/xvdf
        volume_type: gp2
        volume_size: 40
  register: ec2

- name: Aggiunta delle istanze all'host group
  add_host: hostname={{ item.public_dns_name }} groupname=launched
  with_items: "{{ ec2.instances }}"

- name: Attesa che il servizio SSH venga avviato
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: "{{ ec2.instances }}"
